package com.cyc.base.connection;

/*
 * #%L
 * File: WorkerListener.java
 * Project: Base Client
 * %%
 * Copyright (C) 2013 - 2017 Cycorp, Inc.
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

//// EXTERNAL IMPORTS
import java.util.EventListener; 

/** *  <P> This interface is one that must be implemented by anyone
 * wishing to listen in on events generated by a SublWorker.
 *
 * @author tbrussea
 * @version $Id: WorkerListener.java 173132 2017-08-02 00:48:28Z nwinant $
 */
public interface WorkerListener extends EventListener {

  /** This event is fired when a SublWorker is starting the 
   * processing of a SubL task.
   * @param event the event object with details about this event
   */    
  public void notifySublWorkerStarted(WorkerEvent event);

  /** This event is fired when new data becomes available in 
   * the processing of a SubL task.
   * @param event the event object with details about this event
   */
  public void notifySublWorkerDataAvailable(WorkerEvent event);

  /** This event is fired when a SubL task has been terminated
   * for any reason.
   * @param event the event object with details about this event
   */
  public void notifySublWorkerTerminated(WorkerEvent event);

}
